services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "6006:6006"
    container_name: nextjs
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    #開発モード
    command: sh -c "npm run dev"
    #ビルド&起動
    # command: sh -c "npm run build && npm run start"
volumes:
  node_modules:
